version: '3'

services:
  web:
    build: .
    entrypoint: ["./entrypoint.sh"]
    working_dir: /app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    ports:
      - '5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wildfiresDB

volumes:
  postgres_data: