version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: wildfires_web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db
      - rabbit

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=wildfiresDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.9
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: wildfires_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db
      - rabbit

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: wildfires_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db
      - rabbit

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: wildfires_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    ports:
      - 5555:5555
    depends_on:
      - redis
      - db
      - rabbit

volumes:
  postgres_data:
