# Generated by Django 5.0 on 2024-01-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildfiresapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wildfires',
            name='acq_date',
            field=models.DateField(),
        ),
    ]
