# Generated by Django 5.0 on 2024-01-05 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wildfiresapi", "0002_alter_wildfires_acq_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wildfires",
            old_name="type",
            new_name="ftype",
        ),
    ]
