# Generated by Django 5.0 on 2024-01-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildfiresapi', '0003_rename_type_wildfires_ftype'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildfires',
            name='comuna',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
