# Generated by Django 4.2.9 on 2024-01-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wildfiresapi', '0004_wildfires_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='wildfires',
            name='acq_datetime_gmt_3',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
