# Generated by Django 4.2.9 on 2024-02-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wildfiresapi', '0005_wildfires_acq_datetime_gmt_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wildfires',
            name='acq_datetime_gmt_3',
        ),
    ]
